- name: terminate single instance
  hosts: all
  remote_user: ec2-user
  gather_facts: false
  tasks:
    - name: Terminate every running instance in a region. Use with EXTREME caution.
      amazon.aws.ec2_instance:
        state: stopped
        region: us-east-1
        filters:
          instance-state-name: running
      delegate_to: localhost