- name: terminate single instance
  hosts: all
  gather_facts: false
  tasks:
    - name: Terminate every running instance in a region. Use with EXTREME caution.
      amazon.aws.ec2_instance:
        state: running
        region: us-east-1
        filters:
          instance-state-name: stopped
      delegate_to: localhost