- name: Crear usuario en la máquina
  hosts: all
  gather_facts: false
  tasks:
    - name: Crear usuario
      ansible.builtin.user:
        name: autopau
        comment: Usu_ansible
        shell: /bin/bash
        uid: 1050
